In [1]:
# Ziel: Beliebige Symmetrische Matrix diagonalisere.

In [2]:
# Mathe Module importieren
import numpy as np

In [3]:
# Symetrische Matrix definieren

# 10 15 20
# 15 30 25
# 20 25 50

M = np.array([[10., 15., 20.], [15., 30., 25.], [20., 25., 50.]])
print(M)

[[10. 15. 20.]
 [15. 30. 25.]
 [20. 25. 50.]]


In [4]:
# Eigenwerte / Eigenvektoren bestimmen
Eigenwerte, Eigenvektoren = np.linalg.eig(M)
print(Eigenwerte)
print(Eigenvektoren)

[76.32970682  0.49726845 13.17302473]
[[ 0.35242418  0.93228756 -0.08146847]
 [ 0.53022063 -0.27064894 -0.80350186]
 [ 0.77114414 -0.23997722  0.58970132]]


In [5]:
# Inverse von Eigenvektor Matrix
Eigenvektoren_Inverse = np.linalg.inv(Eigenvektoren)
print(Eigenvektoren_Inverse)

[[ 0.35242418  0.53022063  0.77114414]
 [ 0.93228756 -0.27064894 -0.23997722]
 [-0.08146847 -0.80350186  0.58970132]]


In [6]:
# Transponiere von Eigenvektor Matrix
Eigenvektoren_transponiert = np.transpose(Eigenvektoren)
print(Eigenvektoren_transponiert)

[[ 0.35242418  0.53022063  0.77114414]
 [ 0.93228756 -0.27064894 -0.23997722]
 [-0.08146847 -0.80350186  0.58970132]]


In [7]:
# Multiplikation Eigenvektoren Matrix und transponierte Eigenvektor Matrix
M_tM = np.dot(Eigenvektoren, Eigenvektoren_transponiert)
print(np.round(M_tM))

[[ 1.  0. -0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]


In [8]:
D = np.diag(Eigenwerte)
print(D)
S = Eigenvektoren
print(S)
S_1 = np.linalg.inv(Eigenvektoren)
print(S_1)

[[76.32970682  0.          0.        ]
 [ 0.          0.49726845  0.        ]
 [ 0.          0.         13.17302473]]
[[ 0.35242418  0.93228756 -0.08146847]
 [ 0.53022063 -0.27064894 -0.80350186]
 [ 0.77114414 -0.23997722  0.58970132]]
[[ 0.35242418  0.53022063  0.77114414]
 [ 0.93228756 -0.27064894 -0.23997722]
 [-0.08146847 -0.80350186  0.58970132]]


In [9]:
Result = np.dot(np.dot(S, D),S_1)
print(Result)
print(M)

[[10. 15. 20.]
 [15. 30. 25.]
 [20. 25. 50.]]
[[10. 15. 20.]
 [15. 30. 25.]
 [20. 25. 50.]]


In [10]:
from timeit import timeit

In [11]:
%%timeit
# Potenzieren der Matrix Variante 1
M_20_1 = np.linalg.matrix_power(M, 150)
#print(M_20_1)

18 µs ± 1.46 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [12]:
%%timeit
# Potenzieren der Matrix Variante 2
M_20_2 = np.dot(np.dot(S, D**150),S_1)
#print(M_20_2)

5.72 µs ± 76.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
