In [15]:
import numpy as np
# Diagonalisierung funktioniert nicht bei Linear Abhaengige Matrizen

In [3]:
A = np.array([[1,2],[1,2]])
A

array([[1, 2],
       [1, 2]])

In [5]:
eigenwerte, eigenvektoren = np.linalg.eig(A)
print(eigenwerte)

print(eigenvektoren)

[0. 3.]
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [9]:
D = np.diag(eigenwerte)
D

array([[0., 0.],
       [0., 3.]])

In [11]:
S = eigenvektoren
S

array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]])

In [12]:
S_inv = np.linalg.inv(S)
S_inv

array([[-0.74535599,  0.74535599],
       [-0.47140452, -0.94280904]])

In [13]:
S_inv @ S 

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [14]:
S_inv @ D @ S

array([[ 1.        , -1.58113883],
       [-1.26491106,  2.        ]])