In [1]:
import numpy as np
A = np.array([[4,1],[3,0]])
A

array([[4, 1],
       [3, 0]])

In [6]:
eigw, eigv = np.linalg.eig(A)


print(eigw)

print(eigv)

D = np.diag(eigw)

[ 4.64575131 -0.64575131]
[[ 0.84007078 -0.21043072]
 [ 0.54247681  0.97760877]]


In [5]:
eigv_inv = np.linalg.inv(eigv)
print(eigv_inv)

[[ 1.04510774  0.2249599 ]
 [-0.5799321   0.89807344]]


In [9]:
A_diag = np.round(eigv_inv @ D @ eigv)
A_diag

array([[ 4., -1.],
       [-3.,  0.]])