In [2]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sym
from scipy.linalg import expm

In [34]:
A = np.array([[2.,4.],[-1.,3.],[0.,-2.]])
A

array([[ 2.,  4.],
       [-1.,  3.],
       [ 0., -2.]])

In [35]:
S, V, D = np.linalg.svd(A)
display(V)

array([5.47722558, 2.        ])

In [36]:
V = np.diag(V)


In [37]:
V

array([[5.47722558, 0.        ],
       [0.        , 2.        ]])

In [38]:
V_inv = np.linalg.inv(V)
V_inv

array([[0.18257419, 0.        ],
       [0.        , 0.5       ]])

In [44]:
S.shape

(3, 3)

In [54]:
Aplus = D.T @ V_inv @ S.T[:2,:]
Aplus

array([[ 0.31666667, -0.36666667,  0.08333333],
       [ 0.08333333,  0.16666667, -0.08333333]])

In [51]:
Aplus = np.linalg.pinv(A)
Aplus

array([[ 0.31666667, -0.36666667,  0.08333333],
       [ 0.08333333,  0.16666667, -0.08333333]])

In [55]:
Aplus @ A

array([[ 1.00000000e+00, -4.16333634e-16],
       [-2.77555756e-17,  1.00000000e+00]])

In [56]:
A @ Aplus

array([[ 0.96666667, -0.06666667, -0.16666667],
       [-0.06666667,  0.86666667, -0.33333333],
       [-0.16666667, -0.33333333,  0.16666667]])

In [57]:
B = np.array([[2,4],[-1,3],[0,-2]])
v = np.array([1,2,3]).reshape(3,1)
B

array([[ 2,  4],
       [-1,  3],
       [ 0, -2]])

In [58]:
v

array([[1],
       [2],
       [3]])

In [59]:
Binv = np.linalg.pinv(B)
Binv

array([[ 0.31666667, -0.36666667,  0.08333333],
       [ 0.08333333,  0.16666667, -0.08333333]])

In [61]:
Binv @ v

array([[-0.16666667],
       [ 0.16666667]])

In [12]:
# Aufgabe 7
A = np.array([[3,0,0,-1],[0,3,-1,0],[0,-1,3,0],[-1,0,0,3]])
A

array([[ 3,  0,  0, -1],
       [ 0,  3, -1,  0],
       [ 0, -1,  3,  0],
       [-1,  0,  0,  3]])

In [13]:
A.T

array([[ 3,  0,  0, -1],
       [ 0,  3, -1,  0],
       [ 0, -1,  3,  0],
       [-1,  0,  0,  3]])

In [15]:
eigw, eigv = np.linalg.eig(A)
display(eigw, eigv)

array([4., 2., 4., 2.])

array([[ 0.70710678,  0.70710678,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.70710678,  0.70710678],
       [ 0.        ,  0.        ,  0.70710678,  0.70710678],
       [-0.70710678,  0.70710678,  0.        ,  0.        ]])

In [19]:
1 / (2**0.5)

0.7071067811865475