In [1]:
# Modul importieren
import numpy as np

In [2]:
# Matrix erstellen
M = np.array([[0.,2.,0.],[2.,0.,0.],[0.,0.,-1.]])
print(M)

[[ 0.  2.  0.]
 [ 2.  0.  0.]
 [ 0.  0. -1.]]


In [3]:
# Eigenwerte und Eigenvetkoren

eigenwerte, eigenvektoren = np.linalg.eig(M)
print(eigenwerte)
print(eigenvektoren)

[ 2. -2. -1.]
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


In [4]:
# Eigen Basis Vektoren (Whatever) mit Faktor 2 multiplizieren
eigenvektor_2 =  eigenvektoren * 2
print(eigenvektor_2)

[[ 1.41421356 -1.41421356  0.        ]
 [ 1.41421356  1.41421356  0.        ]
 [ 0.          0.          2.        ]]


In [5]:
# Matrix D erstellen
D = np.diag(eigenwerte)
print(D)

[[ 2.  0.  0.]
 [ 0. -2.  0.]
 [ 0.  0. -1.]]


In [6]:
V_1 = eigenvektor_2
V_Inv = np.linalg.inv(eigenvektor_2)
M_1 = V_1 @ D @ V_Inv
print(np.round(M_1))

[[ 0.  2.  0.]
 [ 2. -0.  0.]
 [ 0.  0. -1.]]


In [7]:
V_2 = eigenvektoren
V_2_Inv = eigenvektoren.T
M_2 = V_2 @ D @ V_2_Inv
print(np.round(M_2))

[[ 0.  2.  0.]
 [ 2. -0.  0.]
 [ 0.  0. -1.]]


In [9]:
M_30 = V_2 @ D ** 30 @ V_2_Inv
print(np.round(M_30))

[[1.07374182e+09 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.07374182e+09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
