In [2]:
import numpy as np
import sympy as sym

In [3]:
x, y, z = sym.symbols("x y z")

In [4]:
A = sym.Matrix([[4,0,2],[0,1,0],[2,0,1]])
A

Matrix([
[4, 0, 2],
[0, 1, 0],
[2, 0, 1]])

In [5]:
xv = sym.Matrix([[x],[y],[z]])
xv

Matrix([
[x],
[y],
[z]])

In [6]:
xvT = xv.T
xvT

Matrix([[x, y, z]])

In [10]:
q = xvT * A * xv
q = sym.simplify(q)
q

Matrix([[4*x**2 + 4*x*z + y**2 + z**2]])

In [18]:
M = np.array([[4,0,2],[0,1,0],[2,0,1]])
M

array([[4, 0, 2],
       [0, 1, 0],
       [2, 0, 1]])

In [19]:
eigw, eigv = np.linalg.eig(M)
display(eigw, eigv)

array([5., 0., 1.])

array([[ 0.89442719, -0.4472136 ,  0.        ],
       [ 0.        ,  0.        ,  1.        ],
       [ 0.4472136 ,  0.89442719,  0.        ]])

In [20]:
# Basistransformation
T = eigv
T_inv = np.linalg.inv(eigv)
T_inv

array([[ 0.89442719,  0.        ,  0.4472136 ],
       [-0.4472136 ,  0.        ,  0.89442719],
       [ 0.        ,  1.        ,  0.        ]])

In [22]:
Ab = T_inv @ M @ T
Ab

array([[5., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [24]:
Ab_sym = sym.Matrix(Ab)
Ab_sym

Matrix([
[5.0, 0,   0],
[  0, 0,   0],
[  0, 0, 1.0]])

In [27]:
xvT * Ab_sym * xv

Matrix([[5.0*x**2 + 1.0*z**2]])