# Lösungen zu den Python-Aufgaben aus LE1

In [1]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

## Aufgabe 15

In [2]:
A = np.array([[89,75,22,102],[75,116,27,120],[22,27,33,62],[102,120,62,200]], dtype=np.float)
A

C:\Users\Si Ben Tran\AppData\Local\Temp\ipykernel_22376\4162136719.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  A = np.array([[89,75,22,102],[75,116,27,120],[22,27,33,62],[102,120,62,200]], dtype=np.float)


array([[ 89.,  75.,  22., 102.],
       [ 75., 116.,  27., 120.],
       [ 22.,  27.,  33.,  62.],
       [102., 120.,  62., 200.]])

### a)

Berechung der Eigenwerte und Eigenvektoren:

In [3]:
ew, ev = np.linalg.eig(A)

Eigenwerte:

In [4]:
ew

array([361.75382302,  42.74593101,  26.33718907,   7.16305691])

Eigenvektoren (Spaltenvektoren):

In [5]:
ev

array([[-0.42552429, -0.42476765,  0.76464379, -0.23199439],
       [-0.50507589, -0.54267519, -0.64193252, -0.19576676],
       [-0.20612674,  0.54869183, -0.05515612, -0.80833585],
       [-0.72203822,  0.4733005 ,  0.01415338,  0.50442752]])

### b)

In [6]:
S = np.zeros([ev.shape[1], ev.shape[1]])

for i in range(ev.shape[1]):
    for j in range(ev.shape[1]):
        S[i,j] = np.vdot( ev[:,i], ev[:,j])

np.round( S, 10 )

array([[ 1.,  0., -0., -0.],
       [ 0.,  1., -0.,  0.],
       [-0., -0.,  1.,  0.],
       [-0.,  0.,  0.,  1.]])

Die Skalarprodukte der Eigenvektoren $\mathbf{v}_i$ und $\mathbf{v}_j$ sind gleich null für alle $i\neq j$ und damit stehen alle Eigenvektoren orthogonal zueinander. Die Eigenvektoren stehen orthogonal zueinander, weil die Matrix $A$ symmetrisch ist (Beweis siehe Skript).

Obiger Code ohne `for`-Loops (überlegen Sie sich, warum das das gleiche ist - Hinweis: Definition des Matrizenprodukts):

In [7]:
np.round( np.dot( ev.T, ev ), 10 )

array([[ 1.,  0., -0., -0.],
       [ 0.,  1., -0.,  0.],
       [-0., -0.,  1.,  0.],
       [-0.,  0.,  0.,  1.]])

### c)

In [8]:
V = ev
Vinv = np.linalg.inv(V)
D = np.round( Vinv.dot(A).dot(V), 10 )
D

array([[361.75382302,   0.        ,  -0.        ,  -0.        ],
       [ -0.        ,  42.74593101,  -0.        ,   0.        ],
       [ -0.        ,   0.        ,  26.33718907,   0.        ],
       [  0.        ,   0.        ,  -0.        ,   7.16305691]])

In [9]:
ew

array([361.75382302,  42.74593101,  26.33718907,   7.16305691])

### d)

Matrix $A$ 20x mit sich selbst multiplizieren:

In [10]:
%%timeit
res = np.eye( A.shape[0] )
for i in range(20):
    res = res.dot(A)

20.1 µs ± 509 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [11]:
sp.Matrix(res) # Sympy kann Latex-Ausgabe

NameError: name 'res' is not defined

Mit `np.linalg.matrix_power()`:

In [ ]:
%%timeit
res = np.linalg.matrix_power(A, 20)

In [ ]:
sp.Matrix(res)

Mit berechneter Diagonalmatrix:

In [ ]:
%%timeit
res = Vinv @ D ** 20 @ V

In [ ]:
sp.Matrix(res)

Sind $V, V^{-1}$ und die Diagonalmatrix $D$ schon berechnet, ist der letzte Ansatz der schnellste.

## Aufgabe 16

### a)

In [ ]:
X = np.array([
    [-2, -4, -6, 6, -8, 6, 3, 6, 8, -9, -1, 1, 4, 2, 2, 2, -1, -1, 2, 2],
    [ -3, -7, -13, 16, -14, 14, 6, 11, 18, -19, 5, 0, 3, 3, 6, 8, -3, -1, 0, 9]
])
X.shape

### b)

In [ ]:
plt.scatter(X[0,:], X[1,:])
plt.xlabel("x")
plt.ylabel("y")

Die Punkte sind ungefähr linear verteilt.

### c)

In [ ]:
XXT = np.dot(X, X.T)
sp.Matrix(XXT)

Die Matrix $X\, X^T$ ist symmetrisch, da $(X\, X^T)^T = (X^T)^T X^T = X \, X^T$.

In [ ]:
ew, ev = np.linalg.eig( XXT)
ew

In [ ]:
ev

Die Eigenvektoren sind:

In [ ]:
v1 = ev[:,0]
v2 = ev[:,1]

In [ ]:
sp.Matrix(v1)

In [ ]:
sp.Matrix(v2)

### d)

In [ ]:
plt.figure(figsize=(7,10))
plt.scatter(X[0,:], X[1,:])
plt.xlabel("x")
plt.ylabel("y")
plt.quiver(0, 0, *v1, color="red", scale=3, label="$\lambda_1 = {:.3f}$".format(ew[0]))
plt.quiver(0, 0, *v2, color="green", scale=3, label="$\lambda_1 = {:.3f}$".format(ew[1]))
plt.legend()
plt.gca().set_aspect("equal")

Hier muss das Aspect-Ratio der Koordinatenachsen auf 1:1 gesetzt werden, damit die Vektoren im Verhältnis zu den Datenpunkten korrekt dargestellt werden. Der grüne Eigenvektor zum betragsgrössten Eigenwert zeigt in die Richtung entlang der die Daten verteilt sind ('Richtung mit grösster Varianz') und der rote Eigenvektor zum betragsmässig zweitgrössten Eigenwert zeigt rechtwinkling dazu, in die Richtung mit der zweitgrössten Varianz.

Die Eigenvektoren von $X\, X^T$ zeigen also in die Hauptrichtungen, entlang derer die Daten $X$ verteilt sind. Würden wir alle Punkte auf die Gerade entlang des grünen Eigenvektors projizieren, so könnten wir die Daten in $X$ mit etwas Verlust komprimiert in nur einer Dimension darstellen.