# Lösungen zu den Python-Aufgaben aus LE5

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Aufgabe 5: Beste Approximation einer Matrix X mit einer Matrix mit Rang 2

In [3]:
X = np.array([[6,0,6],[0,12,6],[6,0,9]])
X

array([[ 6,  0,  6],
       [ 0, 12,  6],
       [ 6,  0,  9]])

In [5]:
U, s, VT = np.linalg.svd(X)

In [9]:
S = np.diag(s)
S[2,2] = 0
S

array([[15.76388289,  0.        ,  0.        ],
       [ 0.        , 10.90510044,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

In [10]:
X2 = U.dot(S).dot(VT)
X2

array([[ 5.26203283, -0.29191464,  6.57742831],
       [-0.02942402, 11.98836086,  6.02302306],
       [ 6.58919792,  0.2330666 ,  8.53897738]])