# Lösungen zu den Python-Aufgaben aus LE2

In [41]:
import numpy as np
from scipy.linalg import expm

## Aufgabe 14

### b)

In [42]:
A = np.array([[1,0],[1,-1]])
B = np.array([[2,-1],[-2,3]])

In [43]:
expm( A + B )

array([[ 28.06545077, -14.88394368],
       [-14.88394368,  13.1815071 ]])

In [46]:
expm( B + A )

array([[ 28.06545077, -14.88394368],
       [-14.88394368,  13.1815071 ]])

In [47]:
expm(A) @ expm(B)

array([[ 54.39709043, -47.00803433],
       [ 10.79393111,  -6.59940306]])

In [48]:
expm(B) @ expm(A)

array([[ 34.07399609,  -6.36184564],
       [-50.17535193,  13.72369128]])

Es gilt nicht $e^{A+B} = e^A \, e^B$.

### d)

In [49]:
np.linalg.det( expm(A) )

1.0

In [50]:
np.exp( np.trace(A) )

1.0

In [51]:
np.linalg.det( expm(B) )

148.413159102577

In [52]:
np.exp( np.trace(B) )

148.4131591025766

## Aufgabe 17

### b)

In [55]:
def positiv_definit(A):
    eigvals = np.linalg.eigvals(A)
    return np.all(eigvals>0)

In [61]:
A = np.array([[1,2],[2,1]])
positiv_definit(A)

False

In [62]:
B = np.array([[1,-1],[-1,4]])
positiv_definit(B)

True

In [63]:
C = np.array([[1,0,0],[0,1,1],[0,1,1]])
positiv_definit(C)

False

In [64]:
D = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
positiv_definit(D)

True