In [43]:
import numpy as np
import matplotlib.pyplot as plt

In [40]:
# Uebungsblatt 3 - Aufgabe 7
x = [-2, -4, -6, 6, -8, 6, 3, 6, 8, -9, -1, 1, 4, 2, 2, 2, -1, -1, 2, 2]
y = [-3, -7, -13, 16, -14, 14, 6, 11, 18, -19, 5, 0, 3, 3, 6, 8, -3, -1, 0, 9]

x = np.array(x).reshape(-1,1)
y = np.array(y).reshape(-1,1)

# Matrix erstellen
X = np.hstack([y, x]).T
display(X)
print(X.shape)

array([[ -3,  -7, -13,  16, -14,  14,   6,  11,  18, -19,   5,   0,   3,
          3,   6,   8,  -3,  -1,   0,   9],
       [ -2,  -4,  -6,   6,  -8,   6,   3,   6,   8,  -9,  -1,   1,   4,
          2,   2,   2,  -1,  -1,   2,   2]])

(2, 20)


In [34]:
# X Transponieren
X_T = X.T
print(X_T)
print(X_T.shape)

[[ -3  -2]
 [ -7  -4]
 [-13  -6]
 [ 16   6]
 [-14  -8]
 [ 14   6]
 [  6   3]
 [ 11   6]
 [ 18   8]
 [-19  -9]
 [  5  -1]
 [  0   1]
 [  3   4]
 [  3   2]
 [  6   2]
 [  8   2]
 [ -3  -1]
 [ -1  -1]
 [  0   2]
 [  9   2]]
(20, 2)


In [33]:
# XX^T berechnen
XXT = np.dot(X, X_T)
print(XXT)
print(XXT.shape)

[[1951  866]
 [ 866  422]]
(2, 2)


In [27]:
# Eigenwerte und Eigenvektoren bestimmen
eigenwerte, eigenvektoren = np.linalg.eig(XXT)
print(eigenwerte)
print(eigenvektoren)

[2341.66935988   31.33064012]
[[ 0.91153928 -0.41121301]
 [ 0.41121301  0.91153928]]


In [31]:
# Eigenbasis erstellen mit Eigenvektoren
E = np.diag(eigenwerte)
print(E)

[[2341.66935988    0.        ]
 [   0.           31.33064012]]


In [32]:
# Transformationsbasis erstellen mit Eigenvektoren
T = eigenvektoren
print(T)

[[ 0.91153928 -0.41121301]
 [ 0.41121301  0.91153928]]


In [41]:
# Inverse von T berechnen
T_inv = np.linalg.inv(T)
print(T_inv)

[[ 0.91153928  0.41121301]
 [-0.41121301  0.91153928]]


In [42]:
# Transformieren der Eigenbasis von XXT
Result = T_inv @ E @ T
print(Result)

[[1951. -866.]
 [-866.  422.]]
