In [1]:
import numpy as np

In [18]:
M = np.array([[4,12],[12,11]])
M

array([[ 4, 12],
       [12, 11]])

In [22]:
eigw, eigv = np.linalg.eig(M.T @ M)
display(eigw, eigv)

array([ 25., 400.])

array([[-0.8, -0.6],
       [ 0.6, -0.8]])

In [23]:
S, V, D = np.linalg.svd(M)
V = np.diag(V)
display(S, V, D)

array([[-0.6, -0.8],
       [-0.8,  0.6]])

array([[20.,  0.],
       [ 0.,  5.]])

array([[-0.6, -0.8],
       [ 0.8, -0.6]])

In [26]:
A = np.array([[10,403,233,342,323,432,23,13,23]]).reshape(3,3)
A

array([[ 10, 403, 233],
       [342, 323, 432],
       [ 23,  13,  23]])

In [31]:
eigwA = np.linalg.eigvals(A @ A.T)

In [34]:
eigwA = eigwA ** 0.5

In [37]:
np.diag(eigwA)

array([[752.58833496,   0.        ,   0.        ],
       [  0.        , 244.03291682,   0.        ],
       [  0.        ,   0.        ,   0.8564965 ]])

In [39]:
S, V, D = np.linalg.svd(A)
print(np.diag(V))

[[752.58833496   0.           0.        ]
 [  0.         244.03291682   0.        ]
 [  0.           0.           0.8564965 ]]


array([5.66389202e+05, 5.95520645e+04, 7.33586246e-01])

In [43]:
np.zeros_like(M)

array([[0, 0],
       [0, 0]])