In [1]:
import numpy as np


In [2]:
A = np.array([[1,2,3],[14,13,12]])
A

array([[ 1,  2,  3],
       [14, 13, 12]])

In [3]:
# Gesucht: Singulaerwerte von A
eigenwerteATA = np.linalg.eigvals(A.T @ A)
eigenwerteAAT = np.linalg.eigvals(A @ A.T)

display(eigenwerteAAT, eigenwerteATA)

array([  2.59412907, 520.40587093])

array([ 5.20405871e+02,  2.59412907e+00, -2.27551437e-14])

In [4]:
eigenwerteAAT ** 0.5

array([ 1.61063002, 22.81240607])

In [5]:
eigenwerteATA ** 0.5

C:\Users\Si Ben Tran\AppData\Local\Temp\ipykernel_2976\4094295978.py:1: RuntimeWarning: invalid value encountered in sqrt
  eigenwerteATA ** 0.5


array([22.81240607,  1.61063002,         nan])

In [6]:
S, V, D = np.linalg.svd(A)
display(V)

array([22.81240607,  1.61063002])

In [15]:
B = np.array([[5,0,3],[7,1,0],[12,0,1]])
B

array([[ 5,  0,  3],
       [ 7,  1,  0],
       [12,  0,  1]])

In [16]:
eigwB = np.linalg.eigvals(B)
eigwB

array([ 1.        ,  9.32455532, -3.32455532])

In [17]:
eigwB ** 2

array([ 1.        , 86.94733192, 11.05266808])

In [18]:
SB, VB, DB = np.linalg.svd(B)
display(VB)

array([14.8884572 ,  2.58560598,  0.80528508])

In [40]:
T = np.diag([4,8,10])
T

array([[ 4,  0,  0],
       [ 0,  8,  0],
       [ 0,  0, 10]])

In [41]:
# Eigenwerte von T
eigenwerteT = np.linalg.eigvals(T)
eigenwerteT

array([ 4.,  8., 10.])

In [42]:
# eigenvektoren 
eigw, eigv = np.linalg.eig(T)
eigv

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])